---

- name: Install MySQL
  apt: name={{ item }} state=installed
  with_items:
    - mysql-server
    - python-mysqldb
  tags: packages

- name: Ensure the MySQL service is running
  service: name=mysql state=started enabled=yes

- name: Ensure database is created
  mysql_db: name={{ db_name }} state=present encoding=utf8

- name: Ensure user has access to the database
  mysql_user: name={{ db_user }} password={{ db_password }} priv='{{ db_name }}.*:ALL' state=present
