---

- name: Create gunicorn user
  user: name={{ gunicorn_user }} state=present createhome=no system=yes

- name: Install gunicorn
  pip: virtualenv={{ virtualenv_path }} name=gunicorn executable=pip3

- name: Create the Gunicorn script file
  template: src=run-gunicorn.sh.j2
            dest={{ virtualenv_path }}/bin/gunicorn-start
            owner={{ application_user }}
            group={{ application_group }}
            mode=0755
            backup=yes
  tags: deploy

- name: Create the supervisor configuration file
  template: src=supervisor.conf.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-gunicorn.conf
            backup=no

- supervisorctl:
    name: "{{ application_name|lower }}-gunicorn"
    state: started
