---

- name: Add InfluxDB signing key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add InfluxDB repository
  apt_repository:
    repo: 'deb https://repos.influxdata.com/ubuntu trusty stable'
    state: present

- name: Install InfluxDB packages
  apt:
    name: influxdb
    state: latest
    #force: true
    update_cache: yes

- name: Create InfluxDB configuration file
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify:
    - Restart InfluxDB service

#- name: Modify InfluxDB hostname
#  replace:
#    dest=/etc/influxdb/influxdb.conf
#    regexp='hostname = "localhost"'
#    replace='hostname = "{{ ansible_hostname }}"'
#    backup=yes

- name: Restart InfluxDB service
  service:
    name: influxdb
    state: restarted

- name: Wait for InfluxDB to start
  wait_for:
    port: 8086
    delay: 1

- name: Create InfluxDB database
  command: /usr/bin/influx -execute 'CREATE DATABASE {{ influxdb_name }}'
  #curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE greenhouse"

- name: Create InfluxDB admin user
  command: /usr/bin/influx -execute "CREATE USER {{ influxdb_admin_user }} WITH PASSWORD '{{ influxdb_admin_password }}' WITH ALL PRIVILEGES"

- name: Create InfluxDB user
  command: /usr/bin/influx -execute "CREATE USER {{ influxdb_user }} WITH PASSWORD '{{ influxdb_password }}'"

- name: Create InfluxDB grant
  command: /usr/bin/influx -execute "GRANT ALL ON {{ influxdb_name }} TO {{ influxdb_user }}"

