---

- name: Create a Vagrant VM
  #gather_facts: False
  hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  vars:
    - application_name: changeme
  vars_files:
    - env_vars/vagrant.yml
  roles:
    - base
    #- influxdb
    # - postgresql
    - virtualenv
    - mysql
    #- gunicorn
    - nginx
    #- selenium
